config/routes.rb
Discotheque::Application.routes.draw do
  
  devise_for :users

  resources :albums
  match 'albums/search' => 'albums#search', :as => 'albums_search'

  root :to => 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  
  belongs_to :user
  
  validates_presence_of :user, :band, :title, :cover
  validates_associated :user, :on => :create, :message => "invalid user"
  validates_length_of :band, :minimum => 3, :on => :create, :message => "name too small"
  
  has_attached_file :cover, :styles => {
                                        :medium => "400x400#",
                                        :small => "100x100#",
                                        :thumb => "50x50#"
                                       }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :rememberable, :encryptable
         #:recoverable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :name, :remember_me
  
  # Validations
  validates_presence_of :email, :name
  validates_uniqueness_of :email, :on => :create, :message => "is already taken", :case_sensitive => false
  validates_presence_of :email, :if => :password_present?
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password_present?
  validates_length_of :password, :within => 5..15, :message => "must be between 5 and 15 chars long", :if => :password_present?
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  
  has_many :albums
  
  
  private
  
  def password_present?
    !password.nil?
  end
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
    @albums = current_user.albums.all
  end
  
  def new
    @album = Album.new
  end
  
  def create
    @album = Album.new(params[:album])
    @album.user = current_user
    if @album.save
      flash[:notice] = "Album #{@album.title} added successfully"
      redirect_to album_path(:id => @album.id)
    else
      render :action => 'new'
    end
  end
  
  def show
    @album = Album.find(params[:id])
    if @album
      render
    else
      render :file => 'public/404', :status => 404
    end
  end
  
  def search
    @albums = current_user.albums.find(:all, :conditions => "band LIKE '%#{params[:querystring]}%' OR title LIKE '%#{params[:querystring]}%'")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/albums/_album.html.erb
<li class="album"><%= link_to image_tag(album.cover(:small), :title => "#{album.band} - #{album.title} (#{album.year})"), album_path(:id => album) %></li>

app/views/albums/index.html.erb
<div class="big-wrapper">
  <h1>Your Library</h1>
  <div class="searchbox">
    <%= form_tag albums_search_path %>
      <%= text_field_tag :querystring %>
      <%= submit_tag 'Search' %>
  </div>
  <% if @albums.empty? %>
    <p>You have no album on your library. This is quite boring</p>
  <% else %>
  <library class="container">
    <p><strong><%= @albums.size %></strong> albums</p>
    <ul>
      <%= render :partial => 'album', :collection => @albums %>
    </ul>
  </library>
  <% end %>
</div>

app/views/albums/new.html.erb
<div class="main-form">
  <h2>Add New Album</h2>

  <%= form_for(@album, :url => albums_path) do |f| %>
    <%= error_messages_for @album %>

    <div><%= f.label :band %><br />
    <%= f.text_field :band %></div>
    
    <div><%= f.label :title %><br />
    <%= f.text_field :title %></div>
    
    <div><%= f.label :year %><br />
    <%= f.number_field :year, :min => 1900, :max => 2013 %></div>
    
    <div><%= f.label :cover %><br />
    <%= f.file_field :cover %></div>

    <div><%= f.submit "Add Album" %></div>
  <% end %>

  <div class="form-botton-links">
    <%= link_to "Cancel", albums_path %>
  </div>
</div>

app/views/albums/search.html.erb
<div class="big-wrapper">
  <h1>Your Library</h1>
  <div class="searchbox">
    <%= form_tag albums_search_path %>
      <%= text_field_tag :querystring, params[:querystring] %>
      <%= submit_tag 'Search' %>
  </div>
  <% if @albums.empty? %>
    <p>No albums matched your search "<%= params[:querystring] %>"</p>
  <% else %>
  <library class="container">
    <p>Albums matching your search "<%= params[:querystring] %>"</p>
    <ul>
      <%= render :partial => 'album', :collection => @albums %>
    </ul>
  </library>
  <% end %>
</div>

app/views/albums/show.html.erb
<div class="main-form">
  <h2><%= @album.band %> - <%= @album.title %> (<%= @album.year %>)</h2>
  <p><%= image_tag @album.cover(:medium) %></p>
  <div class="form-botton-links">
    <%= link_to "Go Back", albums_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Discotheque</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <notifications>
    <div>
    <% if notice %><p class="notice"><%= notice %></p><% end %>
    <% if alert %><p class="alert"><%= alert %></p><% end %>
    </div>
  </notifications>
  <status>
    <div>
      <% if user_signed_in? %>
      <box class="left"><%= link_to "Add New Album", new_album_path %></box>
      <box class="right">You are now logged in as <%= current_user.name || current_user.email %> (<%= link_to 'Account', edit_user_registration_path %>) | <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></box>
      <% end %>
    </div>
  </status>
  <header class="logo-wrap">
    <p class='logo top'><%= link_to 'Discotheque', root_path %></p>
  </header>

<%= yield %>

</body>
</html>